apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nexus-operator
    app.kubernetes.io/managed-by: kustomize
  name: nexuscleanuppolicy-admin-role
rules:
- apiGroups:
  - edp.epam.com
  resources:
  - nexuscleanuppolicies
  verbs:
  - '*'
- apiGroups:
  - edp.epam.com
  resources:
  - nexuscleanuppolicies/status
  verbs:
  - get
