apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nexus-operator
    app.kubernetes.io/managed-by: kustomize
  name: nexusrole-admin-role
rules:
- apiGroups:
  - edp.epam.com
  resources:
  - nexusroles
  verbs:
  - '*'
- apiGroups:
  - edp.epam.com
  resources:
  - nexusroles/status
  verbs:
  - get
