apiVersion: v2.edp.epam.com/v1alpha1
kind: Nexus
metadata:
  name: example-nexus
spec:
  image: "sonatype/nexus3"
  version: "3.21.2"
  basePath: ""
  keycloakSpec:
    enabled: false
    url: ""
  volumes:
    - name: "data"
      storage_class: "gp2"
      capacity: "10Gi"
  users:
    - username: test@edp.com
      first_name: ""
      last_name: ""
      email: ""
      roles:
        - edp-admin